---
image: docker:///concourse/static-golang

inputs:
  - name: s3-resource
    path: gopath/src/github.com/concourse/s3-resource

run:
  path: gopath/src/github.com/concourse/s3-resource/scripts/test
